// High-fidelity Mock Data for Military Base Management System
// Falls back automatically if database is not configured or fails.

export const mockPersonnel = [
  {
    id: "user-1",
    name: "João Silva",
    email: "joao.silva@exercito.mil.br",
    warName: "Soldado Silva",
    rank: "SOLDADO",
    militaryId: "RM-209384",
    bloodType: "O+",
    specialty: "Infantaria",
    status: "ATIVO",
    barrackId: "barrack-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-2",
    name: "Marcos Souza",
    email: "marcos.souza@exercito.mil.br",
    warName: "Cabo Souza",
    rank: "CABO",
    militaryId: "RM-192847",
    bloodType: "A-",
    specialty: "Cavalaria",
    status: "ATIVO",
    barrackId: "barrack-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-3",
    name: "Roberto Costa",
    email: "roberto.costa@exercito.mil.br",
    warName: "Sargento Costa",
    rank: "SARGENTO",
    militaryId: "RM-182736",
    bloodType: "B+",
    specialty: "Comunicações",
    status: "FERIAS",
    barrackId: "barrack-2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-4",
    name: "Clara Mendonça",
    email: "clara.mendonca@exercito.mil.br",
    warName: "Tenente Clara",
    rank: "TENENTE",
    militaryId: "RM-102938",
    bloodType: "AB+",
    specialty: "Saúde",
    status: "ATIVO",
    barrackId: "barrack-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "user-5",
    name: "Augusto Neto",
    email: "augusto.neto@exercito.mil.br",
    warName: "Coronel Augusto",
    rank: "CORONEL",
    militaryId: "RM-010293",
    bloodType: "O+",
    specialty: "Comando",
    status: "ATIVO",
    barrackId: "barrack-3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const mockWeapons = [
  {
    id: "weapon-1",
    serialNumber: "FUZ-556-92837",
    type: "FUZIL",
    model: "IA2",
    caliber: "5.56mm",
    status: "DISPONIVEL",
    lastInspection: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "weapon-2",
    serialNumber: "FUZ-762-10293",
    type: "FUZIL",
    model: "IA2",
    caliber: "7.62mm",
    status: "CAUTELADO",
    lastInspection: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "weapon-3",
    serialNumber: "PIS-900-47283",
    type: "PISTOLA",
    model: "PT92",
    caliber: "9mm",
    status: "MANUTENCAO",
    lastInspection: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "weapon-4",
    serialNumber: "FUZ-556-88273",
    type: "FUZIL",
    model: "M4A1",
    caliber: "5.56mm",
    status: "DISPONIVEL",
    lastInspection: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  }
];

export const mockWeaponLoans = [
  {
    id: "loan-1",
    userId: "user-2",
    userName: "Marcos Souza",
    userRank: "CABO",
    weaponId: "weapon-2",
    weaponModel: "IA2 (7.62mm)",
    weaponSerial: "FUZ-762-10293",
    loanOfficerId: "user-3",
    loanOfficerName: "Sargento Costa",
    loanedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    returnedAt: null,
    notes: "Patrulha noturna de rotina.",
  }
];

export const mockVehicles = [
  {
    id: "vehicle-1",
    plate: "EB-20934",
    type: "BLINDADO",
    model: "Guarani VBTP-MR",
    fuelType: "DIESEL",
    odometer: 1200,
    status: "PRONTO",
    fuelLevel: 95,
    createdAt: new Date().toISOString(),
  },
  {
    id: "vehicle-2",
    plate: "EB-10293",
    type: "PATRULHA",
    model: "Agrale Marruá",
    fuelType: "DIESEL",
    odometer: 12500,
    status: "EM_MISSAO",
    fuelLevel: 60,
    createdAt: new Date().toISOString(),
  },
  {
    id: "vehicle-3",
    plate: "EB-30294",
    type: "TRANSPORTE",
    model: "Toyota Hilux",
    fuelType: "GASOLINA",
    odometer: 48000,
    status: "MANUTENCAO",
    fuelLevel: 100,
    createdAt: new Date().toISOString(),
  }
];

export const mockMaintenanceLogs = [
  {
    id: "maint-1",
    vehicleId: "vehicle-3",
    vehicleModel: "Toyota Hilux",
    description: "Revisão dos freios e troca de suspensão dianteira.",
    startDate: new Date(Date.now() - 3600000 * 24).toISOString(),
    endDate: null,
    status: "EM_ANDAMENTO"
  }
];

export const mockBarracks = [
  {
    id: "barrack-1",
    name: "Alojamento Alpha",
    capacity: 20,
    occupiedBeds: 15,
    type: "SOLDADOS",
    createdAt: new Date().toISOString(),
  },
  {
    id: "barrack-2",
    name: "Alojamento Bravo",
    capacity: 10,
    occupiedBeds: 4,
    type: "SARGENTOS",
    createdAt: new Date().toISOString(),
  },
  {
    id: "barrack-3",
    name: "Alojamento Charlie",
    capacity: 5,
    occupiedBeds: 2,
    type: "OFICIAIS",
    createdAt: new Date().toISOString(),
  }
];

export const mockMissions = [
  {
    id: "mission-1",
    name: "Operação Sentinela Verde",
    description: "Patrulhamento preventivo na fronteira amazônica para combate a atividades ilícitas e reconhecimento de terreno.",
    local: "Fronteira Setor Norte - Selva Amazon",
    status: "Em Curso",
    riskLevel: "MEDIO",
    routeCoordinates: JSON.stringify([
      { x: 100, y: 150 },
      { x: 250, y: 120 },
      { x: 400, y: 220 },
      { x: 350, y: 380 },
      { x: 150, y: 300 }
    ]),
    startDate: "2026-05-19T08:00:00.000Z",
    endDate: null as string | null,
    dataFimPrevisa: "2026-05-24T18:00:00.000Z",
    personnel: [
      { userId: "mil-1", warName: "Marinheiro Silva", rank: "Marinheiro", role: "ATIRADOR" },
      { userId: "mil-2", warName: "1º Cabo Souza", rank: "1°Cabo", role: "MOTORISTA" },
      { userId: "mil-4", warName: "Tenente Clara", rank: "Tenente-de-Navio", role: "COMANDANTE" }
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mission-2",
    name: "Patrulha Alpha de Perímetro",
    description: "Varredura rotineira nos arredores das cercas de proteção e pontos de vigia no quadrante sul da base militar.",
    local: "Quadrante Sul - Cercas de Proteção",
    status: "Planejada",
    riskLevel: "BAIXO",
    routeCoordinates: JSON.stringify([
      { x: 50, y: 50 },
      { x: 450, y: 50 },
      { x: 450, y: 450 },
      { x: 50, y: 450 }
    ]),
    startDate: "2026-05-20T10:00:00.000Z",
    endDate: null as string | null,
    dataFimPrevisa: "2026-05-20T16:00:00.000Z",
    personnel: [
      { userId: "mil-3", warName: "Sargento Costa", rank: "1°Sargento", role: "COMANDANTE" }
    ],
    createdAt: new Date().toISOString(),
  }
];

// --- NOVO CADASTRO DE MILITARES MOCKADOS (EFETIVO COMPLETO) ---
export const mockMilitares = [
  {
    id: "mil-1",
    nip: "10938421",
    patente: "Marinheiro",
    tipoPrestacaoServico: "SMO – Serviço Militar Obrigatório",
    formaPrestacaoServico: "SMO",
    nome: "João Pedro da Silva",
    bi: "002938472LA044",
    dataNascimento: "2005-04-12",
    sexo: "M",
    grupoSanguineo: "O+",
    altura: "1.78",
    peso: "72",
    calcado: "41",
    uniforme: "L",
    pai: "Pedro João da Silva",
    mae: "Maria Souza da Silva",
    estadoCivil: "Solteiro(a)",
    endereco: "Rua do Efetivo, Bloco C, Q.12, Luanda",
    telefones: JSON.stringify(["923485712", "912093847"]),
    email: "joao.silva@armada.mil.ao",
    contatoAcidenteNome: "Maria Souza da Silva",
    contatoAcidenteParentesco: "Mãe",
    contatoAcidenteTelefone: "912093847",
    formacaoAcademica: "Ensino Médio Concluído",
    dataIncorporacao: "2024-02-15",
    funcao: "Atirador de Infantaria Fuzileiro",
    formacaoMilitar: "Recruta Fuzileiro Naval de Luanda",
    unidadeMilitar: "1ª Companhia",
    companhia: "1ª Companhia",
    pelotao: "1º Pelotão",
    seccao: "2ª Secção",
    equipa: "Alpha-1",
    dataUltimaPromocao: "2024-02-15",
    situacao: "Missão",
    especialidade: "Fuzileiro Naval",
    foto: "",
    dataPrevisaoRetorno: "2026-05-24",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mil-2",
    nip: "19284732",
    patente: "1°Cabo",
    tipoPrestacaoServico: "SMC – Serviço Militar por Contrato",
    formaPrestacaoServico: "SMC",
    nome: "Marcos Antônio de Souza",
    bi: "001928473LA092",
    dataNascimento: "2002-08-22",
    sexo: "M",
    grupoSanguineo: "A-",
    altura: "1.82",
    peso: "80",
    calcado: "42",
    uniforme: "XL",
    pai: "Antônio Marcos de Souza",
    mae: "Ana Clara de Souza",
    estadoCivil: "Casado(a)",
    endereco: "Condomínio Militar, Casa 18, Lobito",
    telefones: JSON.stringify(["932019284"]),
    email: "marcos.souza@armada.mil.ao",
    contatoAcidenteNome: "Ana Clara de Souza",
    contatoAcidenteParentesco: "Esposa",
    contatoAcidenteTelefone: "932019284",
    formacaoAcademica: "Técnico em Eletro-Mecânica",
    dataIncorporacao: "2022-05-10",
    funcao: "Motorista de Blindado",
    formacaoMilitar: "Curso de Especialização em Blindados Navais",
    unidadeMilitar: "1ª Companhia",
    companhia: "1ª Companhia",
    pelotao: "2º Pelotão",
    seccao: "1ª Secção",
    equipa: "Bravo-2",
    dataUltimaPromocao: "2024-03-01",
    situacao: "Missão",
    especialidade: "Especialista em Viaturas de Transporte",
    foto: "",
    dataPrevisaoRetorno: "2026-05-24",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mil-3",
    nip: "18273645",
    patente: "1°Sargento",
    tipoPrestacaoServico: "QP – Quadro Permanente",
    formaPrestacaoServico: "QP",
    nome: "Roberto Mendes Costa",
    bi: "009182736LA022",
    dataNascimento: "1994-11-05",
    sexo: "M",
    grupoSanguineo: "B+",
    altura: "1.75",
    peso: "78",
    calcado: "40",
    uniforme: "M",
    pai: "José Roberto Costa",
    mae: "Laura Mendes Costa",
    estadoCivil: "Casado(a)",
    endereco: "Bairro do Comando, Apt. 402, Luanda",
    telefones: JSON.stringify(["923984712", "990182736"]),
    email: "roberto.costa@armada.mil.ao",
    contatoAcidenteNome: "Laura Mendes Costa",
    contatoAcidenteParentesco: "Esposa",
    contatoAcidenteTelefone: "990182736",
    formacaoAcademica: "Licenciatura em Ciências Militares",
    dataIncorporacao: "2013-03-01",
    funcao: "Sargento de Transmissões / Efetivo",
    formacaoMilitar: "Academia de Sargentos das Forças Navais",
    unidadeMilitar: "Comando do Batalhão",
    companhia: "Comando do Batalhão",
    pelotao: "Sede",
    seccao: "Sede",
    equipa: "Sede-1",
    dataUltimaPromocao: "2022-09-10",
    situacao: "Férias",
    especialidade: "Telecomunicações Militares",
    foto: "",
    dataPrevisaoRetorno: "2026-06-15",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mil-4",
    nip: "10293847",
    patente: "Tenente-de-Navio",
    tipoPrestacaoServico: "QP – Quadro Permanente",
    formaPrestacaoServico: "QP",
    nome: "Clara Antunes Mendonça",
    bi: "003029384LA011",
    dataNascimento: "1991-03-17",
    sexo: "F",
    grupoSanguineo: "AB+",
    altura: "1.69",
    peso: "61",
    calcado: "37",
    uniforme: "S",
    pai: "Manuel Júlio Mendonça",
    mae: "Helena Antunes Mendonça",
    estadoCivil: "Solteiro(a)",
    endereco: "Vila de Oficiais da Base Naval, Luanda",
    telefones: JSON.stringify(["924857211"]),
    email: "clara.mendonca@armada.mil.ao",
    contatoAcidenteNome: "Helena Antunes Mendonça",
    contatoAcidenteParentesco: "Mãe",
    contatoAcidenteTelefone: "924857211",
    formacaoAcademica: "Licenciatura em Enfermagem",
    dataIncorporacao: "2015-01-20",
    funcao: "Comandante do Pelotão de Saúde",
    formacaoMilitar: "Escola de Formação de Oficiais da Marinha",
    unidadeMilitar: "3ª Companhia",
    companhia: "3ª Companhia",
    pelotao: "3º Pelotão",
    seccao: "3ª Secção",
    equipa: "Charlie-Medic",
    dataUltimaPromocao: "2023-01-20",
    situacao: "Missão",
    especialidade: "Saúde e Medicina de Combate",
    foto: "",
    dataPrevisaoRetorno: "2026-05-24",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mil-5",
    nip: "01029384",
    patente: "Capitão-de-Fragata",
    tipoPrestacaoServico: "QP – Quadro Permanente",
    formaPrestacaoServico: "QP",
    nome: "Augusto Carlos Neto",
    bi: "000102938LA001",
    dataNascimento: "1980-07-30",
    sexo: "M",
    grupoSanguineo: "O+",
    altura: "1.80",
    peso: "85",
    calcado: "41",
    uniforme: "L",
    pai: "Carlos Augusto Neto",
    mae: "Juliana Mendes Neto",
    estadoCivil: "Divorciado(a)",
    endereco: "Bairro de Oficiais Superiores, Casa 3, Luanda",
    telefones: JSON.stringify(["911029384"]),
    email: "augusto.neto@armada.mil.ao",
    contatoAcidenteNome: "Carlos Augusto Neto",
    contatoAcidenteParentesco: "Pai",
    contatoAcidenteTelefone: "911029384",
    formacaoAcademica: "Mestrado em Estratégia e Segurança Marítima",
    dataIncorporacao: "2000-03-01",
    funcao: "Comandante do Batalhão de Fuzileiros",
    formacaoMilitar: "Curso Superior de Comando e Estado-Maior",
    unidadeMilitar: "Comando do Batalhão",
    companhia: "Comando do Batalhão",
    pelotao: "Sede do Batalhão",
    seccao: "Sede do Batalhão",
    equipa: "Sede-Comando",
    dataUltimaPromocao: "2020-05-15",
    situacao: "Missão",
    especialidade: "Doutrina Militar e Estratégia de Fuzileiros",
    foto: "",
    dataPrevisaoRetorno: "2026-06-30",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mil-6",
    nip: "12304928",
    patente: "Grumete",
    tipoPrestacaoServico: "SMO – Serviço Militar Obrigatório",
    formaPrestacaoServico: "SMO",
    nome: "Filipe Eduardo Kanga",
    bi: "005928374LA088",
    dataNascimento: "2006-01-05",
    sexo: "M",
    grupoSanguineo: "AB-",
    altura: "1.74",
    peso: "68",
    calcado: "39",
    uniforme: "M",
    pai: "Eduardo Kanga",
    mae: "Celeste Kanga",
    estadoCivil: "Solteiro(a)",
    endereco: "Rua Direita de Cacuaco, Casa 114, Cacuaco",
    telefones: JSON.stringify(["923485712"]),
    email: "filipe.kanga@armada.mil.ao",
    contatoAcidenteNome: "Celeste Kanga",
    contatoAcidenteParentesco: "Mãe",
    contatoAcidenteTelefone: "923485712",
    formacaoAcademica: "9º Ano Concluído",
    dataIncorporacao: "2025-01-10",
    funcao: "Servente de Metralhadora",
    formacaoMilitar: "Instrução Militar Geral de Grumetes",
    unidadeMilitar: "2ª Companhia",
    companhia: "2ª Companhia",
    pelotao: "1º Pelotão",
    seccao: "3ª Secção",
    equipa: "Bravo-3",
    dataUltimaPromocao: "2025-01-10",
    situacao: "Formação",
    especialidade: "Infantaria Geral",
    foto: "",
    dataPrevisaoRetorno: "2026-08-01",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "mil-7",
    nip: "90293481",
    patente: "Marinheiro",
    tipoPrestacaoServico: "SMC – Serviço Militar por Contrato",
    formaPrestacaoServico: "SMC",
    nome: "Antônio Domingos Manuel",
    bi: "004029481LA043",
    dataNascimento: "2003-10-15",
    sexo: "M",
    grupoSanguineo: "O-",
    altura: "1.85",
    peso: "88",
    calcado: "43",
    uniforme: "XL",
    pai: "Domingos Manuel",
    mae: "Joana Domingos Manuel",
    estadoCivil: "Solteiro(a)",
    endereco: "Bairro Central, Lobito",
    telefones: JSON.stringify(["942039481"]),
    email: "antonio.manuel@armada.mil.ao",
    contatoAcidenteNome: "Joana Domingos Manuel",
    contatoAcidenteParentesco: "Mãe",
    contatoAcidenteTelefone: "942039481",
    formacaoAcademica: "Ensino Médio de Informática",
    dataIncorporacao: "2023-06-15",
    funcao: "Rádio-Operador de Combate",
    formacaoMilitar: "Curso Geral de Operadores de Rádio de Fuzileiros",
    unidadeMilitar: "3ª Companhia",
    companhia: "3ª Companhia",
    pelotao: "2º Pelotão",
    seccao: "1ª Secção",
    equipa: "Charlie-Radio",
    dataUltimaPromocao: "2023-06-15",
    situacao: "Baixa Médica",
    especialidade: "Comunicações Operacionais",
    foto: "",
    dataPrevisaoRetorno: "2026-06-01",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const mockHistoricoEventos = [
  {
    id: "evt-1",
    militarId: "mil-1",
    tipo: "MISSÃO",
    data: "2026-05-19",
    descricao: "Designado para a Operação Sentinela Verde na fronteira norte.",
    detalhes: "Comandante de equipa autorizou fardamento de campanha."
  },
  {
    id: "evt-2",
    militarId: "mil-2",
    militarNome: "Marcos Antônio de Souza",
    tipo: "PROMOÇÃO",
    data: "2024-03-01",
    descricao: "Promovido a 1° Cabo por mérito e conduta de excelência.",
    detalhes: "Certificado emitido pela Direção de Pessoal e Quadros Navais."
  },
  {
    id: "evt-3",
    militarId: "mil-3",
    tipo: "FÉRIAS",
    data: "2026-05-15",
    descricao: "Início do período regulamentar de férias anuais.",
    detalhes: "Previsão de retorno ao serviço ativo em 15 de Junho de 2026."
  },
  {
    id: "evt-4",
    militarId: "mil-4",
    tipo: "LOUVOR",
    data: "2025-12-10",
    descricao: "Elogio público por atuação exemplar em socorro de urgência na base.",
    detalhes: "Louvor assinado pelo Almirante Comandante das Forças Navais."
  },
  {
    id: "evt-5",
    militarId: "mil-5",
    tipo: "PROMOÇÃO",
    data: "2020-05-15",
    descricao: "Promovido a Capitão-de-Fragata com posse de comando.",
    detalhes: "Ordem de serviço número 402/20."
  },
  {
    id: "evt-6",
    militarId: "mil-7",
    tipo: "PUNIÇÃO",
    data: "2025-10-05",
    descricao: "Advertência verbal por atraso de 15 minutos na escala de guarda.",
    detalhes: "Punição de nível leve registada pelo Oficial de Dia."
  }
];

export const mockCourses = [
  {
    id: "course-1",
    name: "Curso de Fuzileiros Navais (CFN)",
    description: "Formação básica e aperfeiçoamento em técnicas de combate anfíbio, patrulha costeira e operações de infantaria naval.",
    instructor: "Capitão-de-Fragata Augusto Carlos Neto",
    durationHours: "360 horas",
    status: "Em Curso",
    startDate: "2026-05-01",
    endDate: "2026-06-15",
    personnel: [
      { userId: "mil-1", warName: "João Pedro", rank: "Marinheiro", role: "ALUNO", status: "Inscrito" },
      { userId: "mil-2", warName: "Marcos Antônio", rank: "1º Cabo", role: "MONITOR", status: "Inscrito" }
    ],
    createdAt: new Date().toISOString()
  },
  {
    id: "course-2",
    name: "Especialização em Armamento e Tiro (CEAT)",
    description: "Instrução avançada de balística, manutenção de armamento e técnicas de precisão de tiro em campo.",
    instructor: "1º Sargento Roberto Mendes Costa",
    durationHours: "120 horas",
    status: "Inscrições Abertas",
    startDate: "2026-06-01",
    endDate: "2026-06-20",
    personnel: [],
    createdAt: new Date().toISOString()
  }
];

// Helper to execute DB query or catch error and return mock
export async function dbQueryWrapper<T>(queryPromise: Promise<T>, mockData: T): Promise<T> {
  try {
    return await queryPromise;
  } catch (error) {
    return mockData;
  }
}
